### ISSUE TITLE
can't connect to APLS when running SN node(error code 6002)

### ISSUE THREAD

**Issue by flik1337** [HewlettPackard/swarm-learning#163]
#  Issue description
- issue description: 
 The SN node failed to started when I run the cancer-pred example. 
  When I check the logs, I found there was the network connection error.
- error messages: 
 Error  code    : 6002
 Error  message : Unable to connect to server. Server might be wrongly configured or down.
 Custom message : Error in communicating With Server https://47.115.216.178:5814
- commands used for starting containers: 
`./scripts/bin/run-sn -d  --name=sn1 --host-ip=43.139.155.29 --sentinel --sn-api-port=30304 --key=workspace/cancer-pred/cert/sn-1-key.pem --cert=workspace/cancer-pred/cert/sn-1-cert.pem --capath=workspace/cancer-pred/cert/ca/capath --apls-ip=47.115.216.178`

# Swarm Learning Version:
- Find the docker tag of the Swarm images ( $ docker images | grep hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning )
hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/sn     1.2.0     cdd30100a28a   3 months ago     hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/sl     1.2.0     22c827268131   3 months ago    hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/swci   1.2.0     01d14d886b16   3 months ago     hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/swop   1.2.0     228c57a1a270   3 months ago    
# OS and ML Platform
- details of host OS:  Ubuntu 18.04, APLS runs in Windows Server

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses?Yes
- If Multiple systems are used, can each system access every other system?Yes
- Is Password-less SSH configuration setup for all the systems?Yes
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them?Yes
- Is the user id a member of the docker group?Yes

# Additional notes
I can access https://47.115.216.178:5814 by Chrome.
<img width="527" alt="image" src="https://user-images.githubusercontent.com/56709053/222952389-ed4a631a-7475-4887-a67f-bd515747aea4.png">

I can connect to https://47.115.216.178:5814 on SL1 machine.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/56709053/222952137-c2e98efd-3407-4404-8223-588b45f4c37a.png">

Here is my Tomcat Conf. The `dev.keystore` was created  following the doc  `How_To_Create_Server_Certificate.pdf`

` <Connector executor="tomcatThreadPool"
               port="5814" protocol="org.apache.coyote.http11.Http11NioProtocol"
               SSLEnabled="true" scheme="https" secure="true"
               sslEnabledProtocols="TLSv1.1+TLSv1.2"  ciphers="TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,SSL_RSA_WITH_RC4_128_SHA"
               clientAuth="false" sslProtocol="TLS"
               keystoreFile="conf/dev.keystore"
               keystorePass="xxxxxxxxxx"
               compression="on" compressionMinSize="128"
               compressibleMimeType="text/html, text/xml,text/plain,text/javascript,text/css,"
               connectionTimeout="20000"
               keepAliveTimeout="1000" server="HPE AutoPass License Server"
               />`

**Comment by flik1337** [comment]
Here is the complete SN1 log .
`######################################################################
##                    HPE SWARM LEARNING SN NODE                    ##
######################################################################
## © Copyright 2019-2022 Hewlett Packard Enterprise Development LP  ##
######################################################################
2023-03-05 12:59:04,301 : swarm.blCnt : INFO : Setting up blockchain layer for the swarm node: START
2023-03-05 12:59:05,300 : swarm.blCnt : INFO : Creating Autopass License Provider
2023-03-05 12:59:05,894 : swarm.blCnt : INFO : Creating license server
2023-03-05 12:59:05,894 : swarm.blCnt : INFO : Setting license servers
2023-03-05 12:59:05,903 : swarm.blCnt : INFO : Acquiring floating license 1100000380:1
Traceback (most recent call last):
  File "AutopassJConcurrent.java", line 359, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 412, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 220, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 277, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 334, in com.hp.autopassj.core.AutopassJConcurrent.checkOutFloatingLicense
  File "LicenseHandler.java", line 1285, in com.hp.autopassj.core.LicenseHandler.checkOut
  File "LicenseHandler.java", line 1249, in com.hp.autopassj.core.LicenseHandler.checkOut
  File "LicenseEnforcer.java", line 779, in com.hp.autopassj.core.enforce.LicenseEnforcer.checkOut
  File "LicenseEnforcer.java", line 201, in com.hp.autopassj.core.enforce.LicenseEnforcer.checkOut
  File "ConcurrentLicense.java", line 91, in com.hp.autopassj.core.license.concurrent.ConcurrentLicense.getLicenses
  File "ConcurrentLicense.java", line 108, in com.hp.autopassj.core.license.concurrent.ConcurrentLicense.getExplicitLicenses
  File "ConcurrentLicense.java", line 210, in com.hp.autopassj.core.license.concurrent.ConcurrentLicense.getAllConcurrentLicenses
  File "FloatingLicenseHandler.java", line 425, in com.hp.autopassj.core.license.server.FloatingLicenseHandler.getFloatingLicense
  File "FloatingLicenseHandler.java", line 152, in com.hp.autopassj.core.license.server.FloatingLicenseHandler.checkOut
  File "ClientRequestResponseHandler.java", line 501, in com.hp.autopassj.core.license.client.ClientRequestResponseHandler.processClientRequest
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_sn.py", line 71, in start_swarm_sn.main
  File "manager.py", line 161, in manager.acquireLicense
  File "alp.py", line 336, in provider.autopass.alp.AutopassLicenseProvider.acquireLicense
  File "alp.py", line 559, in provider.autopass.alp.AutopassLicenseProvider._acquireFloatingLicense
com.hp.autopassj.common.cf.CommunicationException:
 Error  code    : 6002
 Error  message : Unable to connect to server. Server might be wrongly configured or down.
 Custom message : Error in communicating With Server https://47.115.216.178:5814`

**Comment by flik1337** [comment]
I solved this issue by deploying a SSL certificate to my domain.
