### ISSUE TITLE
Running on WSL (Ubuntu 20.04) - Does it work fine ?

### ISSUE THREAD

**Issue by wzp21142** [HewlettPackard/swarm-learning#7]
I want to test this repo in a WSL (Ubuntu 20.04) environment on my PC, I have the APL server running locally and installed the license and confirmed with curl that https://127.0.0.1:5814 is accessible. However, when trying to run mnist-keras with ./mnist-keras/bin/run-sl, the following error occurs:
WARN[0000] Current umask 0022 is too permissive; setting umask 0027
INFO[0000] Starting agent with data directory: "/spire/data/agent"
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=join_token plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=false plugin_name=swarm plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
INFO[0000] Bundle is not found                           subsystem_name=attestor
INFO[0000] SVID is not found. Starting node attestation  subsystem_name=attestor
WARN[0000] Insecure bootstrap enabled; skipping server certificate verification  subsystem_name=attestor
INFO[0000] Node attestation was successful               spiffe_id="spiffe://swarm.learning/spire/agent/join_token/cb782c91-7fe0-448b-94ad-7b9acb12ac99" subsystem_name=attestor
INFO[0000] Starting Workload and SDS APIs                subsystem_name=endpoints
2021-06-26 06:00:53,625 : swarm.mlApp : INFO : Creating Autopass License Provider
Jun 26, 2021 6:00:53 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/platform/swarmml/autopassj/lib/jaxb-impl-2.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-06-26 06:00:54,487 : swarm.mlApp : INFO : Creating license server
2021-06-26 06:00:54,489 : swarm.mlApp : INFO : Setting license servers
2021-06-26 06:00:54,506 : swarm.mlApp : INFO : Acquiring floating license 1100000378:1
Traceback (most recent call last):
  File "AutopassJConcurrent.java", line 359, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 412, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 220, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 277, in com.hp.autopassj.core.AutopassJConcurrent.checkOut
  File "AutopassJConcurrent.java", line 334, in com.hp.autopassj.core.AutopassJConcurrent.checkOutFloatingLicense
  File "LicenseHandler.java", line 1285, in com.hp.autopassj.core.LicenseHandler.checkOut
  File "LicenseHandler.java", line 1249, in com.hp.autopassj.core.LicenseHandler.checkOut
  File "LicenseEnforcer.java", line 779, in com.hp.autopassj.core.enforce.LicenseEnforcer.checkOut
  File "LicenseEnforcer.java", line 201, in com.hp.autopassj.core.enforce.LicenseEnforcer.checkOut
  File "ConcurrentLicense.java", line 91, in com.hp.autopassj.core.license.concurrent.ConcurrentLicense.getLicenses
  File "ConcurrentLicense.java", line 108, in com.hp.autopassj.core.license.concurrent.ConcurrentLicense.getExplicitLicenses
  File "ConcurrentLicense.java", line 210, in com.hp.autopassj.core.license.concurrent.ConcurrentLicense.getAllConcurrentLicenses
  File "FloatingLicenseHandler.java", line 425, in com.hp.autopassj.core.license.server.FloatingLicenseHandler.getFloatingLicense
  File "FloatingLicenseHandler.java", line 152, in com.hp.autopassj.core.license.server.FloatingLicenseHandler.checkOut
  File "ClientRequestResponseHandler.java", line 501, in com.hp.autopassj.core.license.client.ClientRequestResponseHandler.processClientRequest
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_ml.py", line 97, in start_swarm_ml.main
  File "manager.py", line 157, in manager.acquireLicense
  File "alp.py", line 318, in provider.autopass.alp.AutopassLicenseProvider.acquireLicense
  File "alp.py", line 533, in provider.autopass.alp.AutopassLicenseProvider._acquireFloatingLicense
com.hp.autopassj.common.cf.CommunicationException:
 Error  code    : 6002
 Error  message : Unable to connect to server. Server might be wrongly configured or down.
 Custom message : Error in communicating With Server https://127.0.0.1:5814
2021/06/26 06:00:55 exit status 1

I would like to know the reason for this error, is there any other configuration that needs to be done on the APL server after the certificate is installed?

**Comment by suresh-ls** [comment]
WSL is NOT supported yet.

**Comment by wzp21142** [comment]
> WSL is NOT supported yet.

Tried again on the VMware Workstation with Ubuntu 20.04 and got the same error.

**Comment by suresh-ls** [comment]
I am closing this issue as its related to WSL. I am opening a new issue for the license issue for easier tracking. Also would help others searching here! #
