### ISSUE TITLE
Ask for help - Running mnist-keras example

### ISSUE THREAD

**Issue by suresh-ls** [HewlettPackard/swarm-learning#9]
Hello,

The other issue is I want to run mnist-keras. I follow this https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-keras. After first step that I get ws-mnist-keras folder, and I try to run 
./mnist-keras/bin/run-sl --name $TRAINING_NODE-sl --network $EXAMPLE-net --host-ip $TRAINING_NODE-sl --sn-ip node-sn -e MAX_EPOCHS=5 --apls-ip $APLS_IP --serverAddress node-spire -genJoinToken --data-dir $WORKSPACE_DIR/ws-$EXAMPLE/$TRAINING_NODE/app-data --model-dir $WORKSPACE_DIR/ws-$EXAMPLE/$TRAINING_NODE/model --model-program mnist_tf.py --sl-platform TF

but it shows like this 
WARN[0000] Current umask 0022 is too permissive; setting umask 0027 
INFO[0000] Starting agent with data directory: "/spire/data/agent" 
INFO[0000] Plugin loaded                                 built-in_plugin=false plugin_name=swarm plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=join_token plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
INFO[0000] Bundle is not found                           subsystem_name=attestor
INFO[0000] SVID is not found. Starting node attestation  subsystem_name=attestor
2021-06-25 04:59:01,782 : swarm.mlApp : INFO : Creating Autopass License Provider
Jun 25, 2021 4:59:01 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/platform/swarmml/autopassj/lib/jaxb-impl-2.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-06-25 04:59:02,395 : swarm.mlApp : INFO : Creating license server
2021-06-25 04:59:02,396 : swarm.mlApp : INFO : Setting license servers
2021-06-25 04:59:02,405 : swarm.mlApp : INFO : Acquiring floating license 1100000378:1
2021-06-25 04:59:02,966 : swarm.mlApp : ERROR : acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000378:1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_ml.py", line 97, in start_swarm_ml.main
  File "manager.py", line 157, in manager.acquireLicense
  File "alp.py", line 321, in provider.autopass.alp.AutopassLicenseProvider.acquireLicense
  File "swarmutils.py", line 619, in swarmutils.swarmlogger.emitError
RuntimeError: acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000378:1
2021/06/25 04:59:03 exit status 1

What could be the problem?
Thanks

_Originally posted by @difan0224 in https://github.com/HewlettPackard/swarm-learning/issues/5#issuecomment-868209844_

**Comment by suresh-ls** [comment]
User has opened a new issue. Hence closing this duplicate.
